/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visualizador;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class Frame extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    
    ArrayList arrayClientes = new ArrayList();                   //Creacion del arreglo donde se almacenaran los nombres
    ArrayList arrayValores = new ArrayList();                   //Creacion del arreglo donde se almacenaran los valores
    
    DefaultListModel modeloClientes = new DefaultListModel();   //Define un modelo para poderlo añadir al JList
    DefaultListModel modeloValores = new DefaultListModel();    //Define un modelo para poderlo añadir al JList
    
    public Frame() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        this.pintarImagen(jLblImage1, "src/visualizador/pizza3.jpg");
        this.pintarImagen(jLblImage2, "src/visualizador/pizzanew.jpg");
        
        jlClientes.setModel(modeloClientes);                     //le pone el modelo al JList
        jlValores.setModel(modeloValores);                      //le pone el modelo al JList
        jbgGrupoTamano.add(jrbGrande);
        jbgGrupoTamano.add(jrbMediana);
        jbgGrupoTamano.add(jrbPequena);
        jbgGrupoTamano.add(jrbNinguno);
        jbgGrupoPorciones.add(jrb0);
        jbgGrupoPorciones.add(jrb1);
        jbgGrupoPorciones.add(jrb2);
        jbgGrupoPorciones.add(jrb3);
        jrbNinguno.setSelected(true);                           //lo selecciona
        jrb0.setSelected(true);                                 //lo selecciona       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgGrupoTamano = new javax.swing.ButtonGroup();
        jbgGrupoPorciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLblImage1 = new javax.swing.JLabel();
        jLblImage2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpDatosCliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jtxtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtCorreoElectronico = new javax.swing.JTextField();
        jpDatosPedido = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jrbPequena = new javax.swing.JRadioButton();
        jrbNinguno = new javax.swing.JRadioButton();
        jrbGrande = new javax.swing.JRadioButton();
        jrbMediana = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jchbChampinones = new javax.swing.JCheckBox();
        jchbPeperoni = new javax.swing.JCheckBox();
        jchbSalami = new javax.swing.JCheckBox();
        jchbQueso = new javax.swing.JCheckBox();
        jchbGuacamole = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jrb2 = new javax.swing.JRadioButton();
        jrb0 = new javax.swing.JRadioButton();
        jrb1 = new javax.swing.JRadioButton();
        jrb3 = new javax.swing.JRadioButton();
        jrb4 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jcbBebidas = new javax.swing.JComboBox<>();
        jpListado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlValores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlClientes = new javax.swing.JList<>();
        jpBotonesControl = new javax.swing.JPanel();
        jbtnSalir = new javax.swing.JButton();
        jbtnCalcular = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnMostrarListado = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(76, 75, 22));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLblImage1.setBackground(new java.awt.Color(255, 255, 255));
        jLblImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLblImage2.setBackground(new java.awt.Color(255, 255, 255));
        jLblImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(231, 177, 10));

        jLabel1.setFont(new java.awt.Font("GothicE", 1, 36)); // NOI18N
        jLabel1.setText("Pizzeria jhon's");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );

        jpDatosCliente.setBackground(new java.awt.Color(137, 129, 33));
        jpDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("GothicE", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("GothicE", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("GothicE", 1, 14)); // NOI18N
        jLabel3.setText("Direccción");

        jLabel4.setFont(new java.awt.Font("GothicE", 1, 14)); // NOI18N
        jLabel4.setText("Telefono");

        jLabel5.setFont(new java.awt.Font("GothicE", 1, 14)); // NOI18N
        jLabel5.setText("correo electronico");

        javax.swing.GroupLayout jpDatosClienteLayout = new javax.swing.GroupLayout(jpDatosCliente);
        jpDatosCliente.setLayout(jpDatosClienteLayout);
        jpDatosClienteLayout.setHorizontalGroup(
            jpDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosClienteLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jpDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19))
        );
        jpDatosClienteLayout.setVerticalGroup(
            jpDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jtxtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpDatosPedido.setBackground(new java.awt.Color(137, 129, 33));
        jpDatosPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("GothicE", 1, 18))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(247, 241, 229));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tamaño", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("GothicE", 1, 14))); // NOI18N

        jrbPequena.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jrbPequena.setText("Pequeña");

        jrbNinguno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jrbNinguno.setText("Ninguno");

        jrbGrande.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jrbGrande.setText("Grande");

        jrbMediana.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jrbMediana.setText("Mediana");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbPequena)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jrbGrande)
                        .addComponent(jrbMediana)
                        .addComponent(jrbNinguno)))
                .addGap(0, 75, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbNinguno)
                .addGap(18, 18, 18)
                .addComponent(jrbGrande)
                .addGap(18, 18, 18)
                .addComponent(jrbMediana)
                .addGap(18, 18, 18)
                .addComponent(jrbPequena)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(247, 241, 229));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Adiciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("GothicE", 1, 14))); // NOI18N

        jchbChampinones.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jchbChampinones.setText("Champiñones");

        jchbPeperoni.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jchbPeperoni.setText("Peperoni");

        jchbSalami.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jchbSalami.setText("Salami");

        jchbQueso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jchbQueso.setText("Queso");

        jchbGuacamole.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jchbGuacamole.setText("Guacamole");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchbChampinones)
                    .addComponent(jchbSalami)
                    .addComponent(jchbQueso)
                    .addComponent(jchbPeperoni)
                    .addComponent(jchbGuacamole))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchbChampinones)
                .addGap(18, 18, 18)
                .addComponent(jchbSalami)
                .addGap(18, 18, 18)
                .addComponent(jchbQueso)
                .addGap(18, 18, 18)
                .addComponent(jchbGuacamole)
                .addGap(18, 18, 18)
                .addComponent(jchbPeperoni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(247, 241, 229));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Porciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("GothicE", 1, 14))); // NOI18N

        jrb2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jrb2.setText("2");

        jrb0.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jrb0.setText("0");

        jrb1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jrb1.setText("1");

        jrb3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jrb3.setText("3");

        jrb4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jrb4.setText("4");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb0)
                    .addComponent(jrb1)
                    .addComponent(jrb2)
                    .addComponent(jrb3)
                    .addComponent(jrb4))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jrb0)
                .addGap(18, 18, 18)
                .addComponent(jrb1)
                .addGap(18, 18, 18)
                .addComponent(jrb2)
                .addGap(18, 18, 18)
                .addComponent(jrb3)
                .addGap(18, 18, 18)
                .addComponent(jrb4)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(247, 241, 229));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Bebidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("GothicE", 1, 14))); // NOI18N

        jcbBebidas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jcbBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Gaseosa", "Malteada", "Cerveza", "Limonada" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpListado.setBackground(new java.awt.Color(247, 241, 229));
        jpListado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Listado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("GothicE", 1, 14))); // NOI18N

        jlValores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jScrollPane1.setViewportView(jlValores);

        jlClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jScrollPane2.setViewportView(jlClientes);

        javax.swing.GroupLayout jpListadoLayout = new javax.swing.GroupLayout(jpListado);
        jpListado.setLayout(jpListadoLayout);
        jpListadoLayout.setHorizontalGroup(
            jpListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpListadoLayout.setVerticalGroup(
            jpListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpDatosPedidoLayout = new javax.swing.GroupLayout(jpDatosPedido);
        jpDatosPedido.setLayout(jpDatosPedidoLayout);
        jpDatosPedidoLayout.setHorizontalGroup(
            jpDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpDatosPedidoLayout.setVerticalGroup(
            jpDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jpBotonesControl.setBackground(new java.awt.Color(247, 241, 229));

        jbtnSalir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jbtnCalcular.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jbtnCalcular.setText("Calcular");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });

        jbtnNuevo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jbtnNuevo.setText("Nuevo");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });

        jbtnMostrarListado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jbtnMostrarListado.setText("Listar");
        jbtnMostrarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostrarListadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotonesControlLayout = new javax.swing.GroupLayout(jpBotonesControl);
        jpBotonesControl.setLayout(jpBotonesControlLayout);
        jpBotonesControlLayout.setHorizontalGroup(
            jpBotonesControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotonesControlLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jbtnCalcular)
                .addGap(18, 18, 18)
                .addComponent(jbtnNuevo)
                .addGap(18, 18, 18)
                .addComponent(jbtnMostrarListado)
                .addGap(18, 18, 18)
                .addComponent(jbtnSalir)
                .addGap(43, 43, 43))
        );
        jpBotonesControlLayout.setVerticalGroup(
            jpBotonesControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotonesControlLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jpBotonesControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSalir)
                    .addComponent(jbtnCalcular)
                    .addComponent(jbtnNuevo)
                    .addComponent(jbtnMostrarListado))
                .addGap(33, 33, 33))
        );

        lblValor.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblValor.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("Valor $");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpDatosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jpBotonesControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jLblImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpDatosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpBotonesControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarControles();
        
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnMostrarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarListadoActionPerformed
        // TODO add your handling code here:
        int i;
        modeloClientes.removeAllElements();
        modeloValores.removeAllElements();
        for(i = 0; i < arrayClientes.size(); i++){
            modeloClientes.addElement(arrayClientes.get(i));
            modeloValores.addElement(arrayValores.get(i));
        }
    }//GEN-LAST:event_jbtnMostrarListadoActionPerformed

    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
        // TODO add your handling code here:
        int vrTamanio, vrPorcion, vrChamp, vrGuacam, vrPeper, vrQues, vrSalam, vrBebida, vrTotal;
        String datoCliente, datoValor;

        vrTamanio = vrPorcion = vrChamp = vrGuacam = vrPeper = vrQues = vrSalam = vrBebida = 0;
        if(jrbGrande.isSelected()) {
            vrTamanio=25000;
        }
        else
        {
            if(jrbMediana.isSelected()) {
                vrTamanio = 15000;
            }
            else
            {
                if(jrbPequena.isSelected()) {
                    vrTamanio = 8000;
                }
            }
        }
        if(jrb1.isSelected()) {
            vrPorcion = 3000; 
        }
        else
        {
            if(jrb2.isSelected()) {
                vrPorcion = 6000;
            }
            else
            {
                if(jrb3.isSelected()) {
                    vrPorcion = 9000;
                }
                else{
                    if(jrb4.isSelected()){
                        vrPorcion = 12000;
                    }
                }
            }
        }
        if(jchbChampinones.isSelected()) {
            vrChamp = 2000;
        }
        if(jchbGuacamole.isSelected()) {
            vrGuacam = 2000;
        }
        if(jchbPeperoni.isSelected()) {
            vrPeper = 2000;
        }
        if(jchbQueso.isSelected()) {
            vrQues = 2000;
        }
        if(jchbSalami.isSelected()) {
            vrSalam = 2000;
        }
        switch(jcbBebidas.getSelectedIndex())
        {
            case 0:
                vrBebida = 0;
                break;
            case 1:
                vrBebida = 2000;
                break;
            case 2:
                vrBebida = 2500;
                break;
            case 3:
                vrBebida = 3500;
                break;
            case 4:
                vrBebida = 3000;
                break;
            case 5:
                vrBebida = 4000;
                break;
            default:break;
        }

        vrTotal = vrTamanio+vrPorcion+vrChamp+vrGuacam+vrPeper+vrQues+vrSalam+vrBebida;
        lblValor.setText(Integer.toString(vrTotal));
        datoCliente = jtxtNombre.getText();
        arrayClientes.add(datoCliente);
        datoValor = lblValor.getText();
        arrayValores.add(datoValor);
    }//GEN-LAST:event_jbtnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    
    public void limpiarControles(){
        jtxtNombre.setText("");
        jtxtDireccion.setText("");
        jtxtCorreoElectronico.setText("");
        jtxtTelefono.setText("");
        jrb0.setSelected(true);
        //jrb1.setSelected(false);
        //jrb2.setSelected(false);
        //jrb3.setSelected(false);
        //jrb4.setSelected(false);
        jrbNinguno.setSelected(true);
        //jrbGrande.setSelected(false);
        //jrbMediana.setSelected(false);
        //jrbPequena.setSelected(false);
        jcbBebidas.setSelectedIndex(0);
        jchbChampinones.setSelected(false);
        jchbGuacamole.setSelected(false);
        jchbPeperoni.setSelected(false);
        jchbQueso.setSelected(false);
        jchbSalami.setSelected(false);
        jtxtNombre.requestFocusInWindow();
        
    }
    
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT
                )
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLblImage1;
    private javax.swing.JLabel jLblImage2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jbgGrupoPorciones;
    private javax.swing.ButtonGroup jbgGrupoTamano;
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JButton jbtnMostrarListado;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcbBebidas;
    private javax.swing.JCheckBox jchbChampinones;
    private javax.swing.JCheckBox jchbGuacamole;
    private javax.swing.JCheckBox jchbPeperoni;
    private javax.swing.JCheckBox jchbQueso;
    private javax.swing.JCheckBox jchbSalami;
    private javax.swing.JList<String> jlClientes;
    private javax.swing.JList<String> jlValores;
    private javax.swing.JPanel jpBotonesControl;
    private javax.swing.JPanel jpDatosCliente;
    private javax.swing.JPanel jpDatosPedido;
    private javax.swing.JPanel jpListado;
    private javax.swing.JRadioButton jrb0;
    private javax.swing.JRadioButton jrb1;
    private javax.swing.JRadioButton jrb2;
    private javax.swing.JRadioButton jrb3;
    private javax.swing.JRadioButton jrb4;
    private javax.swing.JRadioButton jrbGrande;
    private javax.swing.JRadioButton jrbMediana;
    private javax.swing.JRadioButton jrbNinguno;
    private javax.swing.JRadioButton jrbPequena;
    private javax.swing.JTextField jtxtCorreoElectronico;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtTelefono;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
